### ISSUE TITLE
Project 5 : Uploading image to firebase 

### ISSUE THREAD

**Issue by sandeepkambham08** [Aimanski12/web_dev_projects#10]
Hello,

Firstly, your work is great!

I am also trying to upload the snap from camera to firebase - similar to what you have done.  
But, I am a bit confused with the base64 data we get from the snap. 

May I know what did you do exactly in the cloudfunction - (in https://us-central1-camera-proj.cloudfunctions.net/storeImage)?  

How can we use the base64 data to store the image in firebase Storage ?

**Comment by Aimanski12** [comment]
too late opened. no needed response

**Comment by Aimanski12** [comment]
_
