### ISSUE TITLE
Looking for freelancer to create a barcode reader component ( react/redux, react router, quagga)

### ISSUE THREAD

**Issue by JP-42** [Aimanski12/web_dev_projects#11]
Hi Aiman,
Just had a look at your barcode scanner web app. Great stuff ! My company is currently building a PWA with reactjs. We need a barcode reader component that works with quagga, react/redux and react router. Basically, we want to :
 - capture the product's ean
 - save it into a redux state
 - navigate to another page

So basically, it is not far of what you already did. Please could you let me know if you could be interested/available to do this on a freelance basis. Is so, I can send you more specs and organize a call. you can reach me by email at john.pete@digisquare.fr or whatsapp 0033 6 3355 6118

All the best,
John

**Comment by Aimanski12** [comment]
no response needed
